# Generated by Django 2.2.10 on 2020-06-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='is_main',
            field=models.BooleanField(unique=True),
        ),
    ]
