# Generated by Django 2.2.10 on 2020-06-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200615_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='is_main',
            field=models.BooleanField(),
        ),
    ]
